basicforms/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'
urlpatterns = [
    path(r'', views.form_name_view, name='form-page'),
    path(r'sign_up', views.form_signUp_view, name="form-sign-up"),
]

basicforms/basicforms/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('formpage/', include('basicapp.urls')),
]

basicforms/basicapp/models.py
from django.db import models

# Create your models here.


class SignUp(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()

basicforms/basicapp/forms.py
from django import forms
from django.core import validators
from .models import SignUp

# We create method "check_for_z" to check if the first character in the input
# is a letter 'z' or 'Z'
def check_for_z(value):
    if value[0].lower() != 'z':
        print("Need to start with z or Z ", value)
        raise forms.ValidationError("Need to start with z or Z")


class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Re-enter email")
    text = forms.CharField(widget=forms.Textarea)
    # We create an input and pass to its validator the method "check_for_z"
    refree = forms.CharField(max_length=24, validators=[check_for_z])
    # We can also have a single validator for all fields at once

    # Each field has certain default validation check.
    # We can also add custom Validation
    # Eg. Lets demonstrate botcather

    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[
                                 validators.MaxLengthValidator(0)])
    # Hidden input widget hides the field from rendering.
    # But the field will be present in HTML element which a bot uses

    # Define a method starting with clean_<field_name>.
    # Django will automatically look for this method while Validation
    def clean_botcatcher(self):
        botcather = self.cleaned_data['botcatcher']
        if len(botcather):
            raise forms.ValidationError("Gotcha Bot!")
        return botcather

    def clean(self):
        # grab all clean data
        all_clean_data = super().clean()

        # Prints only clean data
        print("Clean data:", super().clean())

        if 'email' in all_clean_data and 'verify_email' in all_clean_data:
            if all_clean_data['email'] != all_clean_data['verify_email']:
                raise forms.ValidationError("Make sure emails are same")


class Form_SignUp(forms.ModelForm):
    # Can have validators/other modifications here. Not Compulsory.
    name = forms.CharField(label="Name", widget=forms.TextInput(
        attrs={'placeholder': 'Name'}))
    # field names and form names should match
    class Meta:
        model = SignUp  # Assign model
        fields = "__all__"  # All fields in model
        # exclude = [exclude1,exclude2] #All model fields except
        # fields = (include1,include2) #Only these model fields

basicforms/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "basicapp/index.html")


from .forms import FormName, Form_SignUp
def form_name_view(request):
    form = FormName()

    if request.method == "POST":
        form = FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS!")
            print("Name", form.cleaned_data['name'])
            print("Email", form.cleaned_data['email'])
            print("Text", form.cleaned_data['text'])
            print("Refree", form.cleaned_data['refree'])
        else:
            print("ERROR!!", form.cleaned_data['name'])
    else:
        print("REQUEST METHOD: ", request.method)

    form_dict = {"form": form}
    return render(request, "basicapp/form_page.html", context=form_dict)


def form_signUp_view(request):
    form = Form_SignUp()

    if request.method == 'POST':
        form = Form_SignUp(request.POST)

        if form.is_valid():
            form.save(commit=True)  # Save form to database
            return index(request)
        else:
            print("Invalid")

    form_dict = {"form": form}
    return render(request, 'basicapp/form_signUp.html', context=form_dict)

basicforms/templates/basicapp/form_page.html
{% extends "fragment/header.html" %}
  {% block body_block %}
    <h1>Fill out the form</h1>
    <form class="" action="" method="POST">
      <!-- format the form -->
      {{ form.as_p }}
      <!-- Ensure the security of the form submitting -->
      {% csrf_token %}
      <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
  {% endblock %}

basicforms/templates/basicapp/form_signUp.html
{% extends "fragment/header.html" %}
  {% block body_block %}
    <h1>Sign up form</h1>
    <form class="" action="" method="POST">
      <!-- format the form -->
      {{ form.as_p }}

      <!-- Ensure the security of the form submitting -->
      {% csrf_token %}
      <input class="btn btn-primary" type="submit" value="Sign up" />
    </form>
  {% endblock %}

basicforms/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "fragment/header.html" %} 
  {% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to homepage of basic app</h1>
    <h2>Go to /sign_up to fill out the form</h2>
    <div>
      <a href="{% url 'basicapp:form-sign-up' %}">Link to the sign-up page</a>
    </div>
  </div>
  {% endblock %}

basicforms/templates/fragment/header.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <title>Page d'accueil</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend!! -->
      {% endblock %}
    </div>
  </body>
</html>

basicforms/templates/fragment/navbar.html
<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li class="navbar-brand"><a href="#">BRAND</a></li>
        <li class="navbar-link"><a href="#">Admin</a></li>
        <li class="navbar-link"><a href="#">Home</a></li>
        <li class="navbar-link"><a href="#">Sign up</a></li>
      </ul>
    </div>
  </nav>

  <div class="container">
    
  </div>
</body>